import { ArrowRight, MessagesSquare, QrCode, Smartphone, Sparkles } from "lucide-react";
import { Reveal } from "@/components/ui/reveal";

const items = [
  { title: "Processing", copy: "Slides and notes are consolidated into one grounded context." },
  { title: "Clarification workspace", copy: "Speaker review improves relevance and confidence before sharing." },
  { title: "Audience access", copy: "The room scans one QR code to open a chatbot that answers from the presentation." },
];

export function WorkflowPreview() {
  return (
    <section id="workflow" className="py-24 md:py-32"><div className="container-shell"><Reveal><span className="eyebrow"><Sparkles className="h-3.5 w-3.5" /> Workflow preview</span><h2 className="section-title mt-6">What happens after upload feels visible, strategic, and complete.</h2><p className="section-copy">The product should telegraph the next steps instantly: a short processing moment, a focused clarification workspace, and a final QR share point for the room.</p></Reveal><div className="mt-14 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><Reveal delay={0.08}><div className="glass-panel overflow-hidden p-6 md:p-7"><div className="grid gap-4 md:grid-cols-[0.8fr_auto_0.8fr_auto_0.8fr]">{items.map((item, index) => <div key={item.title} className="contents"><div className="rounded-[24px] border border-white/8 bg-white/6 p-5"><div className="text-xs uppercase tracking-[0.24em] text-orange-300">0{index + 1}</div><div className="mt-4 text-xl font-semibold text-white">{item.title}</div><p className="mt-3 text-sm text-white/64">{item.copy}</p></div>{index < items.length - 1 ? <div className="hidden items-center justify-center md:flex"><ArrowRight className="h-6 w-6 text-white/30" /></div> : null}</div>)}</div></div></Reveal><Reveal delay={0.16}><div className="glass-panel relative overflow-hidden p-6"><div className="absolute right-6 top-6 rounded-full border border-orange-400/20 bg-orange-500/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.24em] text-orange-200">Audience preview</div><div className="mx-auto mt-10 max-w-[290px] rounded-[34px] border border-white/10 bg-navy-950/88 p-3 shadow-royal"><div className="rounded-[28px] border border-white/8 bg-gradient-to-b from-royal-600/20 to-navy-950 p-4"><div className="flex items-center justify-between"><div className="text-sm font-semibold text-white">AutoQ&A</div><Smartphone className="h-4 w-4 text-orange-300" /></div><div className="mt-5 rounded-[22px] border border-white/8 bg-white/5 p-4"><div className="flex items-center gap-2 text-sm font-medium text-white"><QrCode className="h-4 w-4 text-orange-300" /> Scan to ask live</div><p className="mt-2 text-xs leading-6 text-white/58">Questions are answered from the presenter’s uploaded material and approved clarifications.</p></div><div className="mt-4 space-y-3"><div className="rounded-[18px] bg-white/6 p-3 text-sm text-white/82">What problem does this solution address?</div><div className="rounded-[18px] bg-royal-500/20 p-3 text-sm text-white/88">Answering from approved slides 2–7. No unsupported assumptions.</div><div className="rounded-[18px] bg-white/6 p-3 text-sm text-white/82">What is intentionally out of scope?</div></div><div className="mt-4 flex items-center gap-2 rounded-full border border-white/8 bg-white/4 px-4 py-3 text-xs text-white/60"><MessagesSquare className="h-4 w-4 text-orange-300" /> Grounded audience chat preview</div></div></div></div></Reveal></div></div></section>
  );
}
